lib/car_dealership_web/router.ex
defmodule CarDealershipWeb.Router do
  use CarDealershipWeb, :router

  import CarDealershipWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {CarDealershipWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CarDealershipWeb do
    pipe_through :browser

    live "/categories", CategoryLive.Index, :index
    live "/categories/new", CategoryLive.Index, :new
    live "/categories/:id/edit", CategoryLive.Index, :edit

    live "/categories/:id", CategoryLive.Show, :show
    live "/categories/:id/show/edit", CategoryLive.Show, :edit

    live "/categories/:id/models", CategoryLive.Show, :add_models

    # live "/categories/:id/models/:model_id", ModelLive.Show, :show
    live "/models/:id/add_cars", ModelLive.Show, :add_cars

    live "/models", ModelLive.Index, :index
    live "/models/new", ModelLive.Index, :new
    live "/models/:id/edit", ModelLive.Index, :edit

    live "/cars/:id", ModelLive.Show, :show
    live "/cars/:id/add_quote", ModelLive.Show, :add_quote
    live "/cars/:id/book_test_drive", ModelLive.Show, :book_test_drive
    live "/models/:id/show/edit", ModelLive.Show, :edit



    live "/models/:id/models", ModelLive.Show, :add_models

    live "/", HomeLive.Index, :index

    live "/listings", ListingLive.Index, :index

    live "/blogs", BlogLive.Index, :index
    live "/blogs/new", BlogLive.Index, :new
    live "/blogs/:id/edit", BlogLive.Index, :edit

    live "/blogs/:id", BlogLive.Show, :show
    live "/blogs/:id/show/edit", BlogLive.Show, :edit

    live "/quotes", QuoteLive.Index, :index
    live "/quotes/new", QuoteLive.Index, :new
    live "/quotes/:id/edit", QuoteLive.Index, :edit

    live "/quotes/:id", QuoteLive.Show, :show
    live "/quotes/:id/show/edit", QuoteLive.Show, :edit
    # live "/cars", CarLive.Index, :index
    # # live "/cars/new", CarLive.Index, :new
    # # live "/cars/:id/edit", CarLive.Index, :edit

    # live "/cars/:id", CarLive.Show, :show
    # live "/cars/:id/show/edit", CarLive.Show, :edit

    live "/drives", DriveLive.Index, :index
    live "/drives/new", DriveLive.Index, :new
    live "/drives/:id/edit", DriveLive.Index, :edit

    live "/drives/:id", DriveLive.Show, :show
    live "/drives/:id/show/edit", DriveLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", CarDealershipWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", CarDealershipWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", CarDealershipWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/dashboard", DashboardLive.Index, :index

    live "/users", UsersLive.Index, :index
  end

  scope "/", CarDealershipWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/car_dealership_web/views/layout_view.ex
defmodule CarDealershipWeb.LayoutView do
  use CarDealershipWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/car_dealership_web/templates/layout/app.html.heex
<main>
  <%= @inner_content %>
</main>

lib/car_dealership_web/templates/layout/dashboard_live.html.heex
<main>
  <%= if @flash["info"] do %>
    <p
      class="alert alert-info hideMsg"
      role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="info"
    >
      <%= live_flash(@flash, :info) %>
    </p>
  <% end %>

  <%= if @flash["error"] do %>
    <p
      class="alert alert-danger hideMsg"
      role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="error"
    >
      <%= live_flash(@flash, :error) %>
    </p>
  <% end %>
  <div class="bg-[#F5F6FA] w-[100%] flex  ">
    <div class="w-[20%] m-4 rounded-md fixed h-[90vh] jakrata-regular hidden gap-4  md:flex text-xl flex-col justify-start p-4 bg-white  bg-cover">
      <%= if @url == "/dashboard" do %>
        <%= live_redirect to: Routes.dashboard_index_path(@socket, :index) do %>
          <div class="flex gap-2  bg-green-500 text-white rounded-md   p-2 items-center">
            <%= Heroicons.icon("table-cells",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              Dashboard
            </p>
          </div>
        <% end %>
      <% else %>
        <%= live_redirect to: Routes.dashboard_index_path(@socket, :index)  do %>
          <div class="flex gap-2   p-2 items-center">
            <%= Heroicons.icon("table-cells",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              Dashboard
            </p>
          </div>
        <% end %>
      <% end %>



      <%= if @url == "/users" do %>
        <%= live_redirect to: Routes.users_index_path(@socket, :index)  do %>
          <div class="flex gap-2  bg-green-500 text-white rounded-md   p-2 items-center">
            <%= Heroicons.icon("user-group",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              System Users
            </p>
          </div>
        <% end %>
      <% else %>
        <%= live_redirect to: Routes.users_index_path(@socket, :index)  do %>
          <div class="flex gap-2   p-2 items-center">
            <%= Heroicons.icon("user-group",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              System Users
            </p>
          </div>
        <% end %>
      <% end %>

      <%= link(to: Routes.user_settings_path(@socket, :edit))  do %>
        <div class="flex gap-2   p-2 items-center">
          <%= Heroicons.icon("cog-6-tooth",
            type: "solid",
            class: "h-8   font-bold w-6"
          ) %>
          <p>
            Settings
          </p>
        </div>
      <% end %>
      <%= link to: Routes.user_session_path(@socket, :delete), method: :delete  do %>
        <div class="flex gap-2   p-2 items-center">
          <%= Heroicons.icon("power",
            type: "solid",
            class: "h-6   font-bold w-6"
          ) %>
          <p>
            Logout
          </p>
        </div>
      <% end %>
    </div>
  <div class="flex w-[100%] overflow-scroll m-4  min-h-[100vh] ml-[25%] flex-col gap-4">
      <div class="flex w-[100%] justify-between text-4xl allura">
        <p>
           <a
      href="/"
      class="text-[#000] allura  md:text-xl text-xs uppercase hover:scale-105 transition-all duration-500 ease-in-out  md:ml-8 ml-2"
    >
      Car dealership
    </a>
        </p>

        
      </div>

      <div class="w-[100%] flex justify-between ">
        <p class="text-gray-600 font-bold text-3xl ">
          <%= @url |> String.replace("/", "") |> String.replace("_", "") |> String.capitalize() %>
        </p>

        <div class="flex gap-2 items-center">
          <p class="bg-green-500 uppercase w-[50px] flex flex-col justify-center items-center h-[50px]  rounded-full text-2xl text-white font-semibold ">
            <%= @current_user.email |> String.at(0) %>
          </p>
        </div>
      </div>

      <%= @inner_content %>
    </div>
  </div>
  
</main>

lib/car_dealership_web/templates/layout/live.html.heex
<main>
  <%= if @flash["info"] do %>
    <p
      class="alert alert-info hideMsg"
      role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="info"
    >
      <%= live_flash(@flash, :info) %>
    </p>
  <% end %>

  <%= if @flash["error"] do %>
    <p
      class="alert alert-danger hideMsg"
      role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="error"
    >
      <%= live_flash(@flash, :error) %>
    </p>
  <% end %>

  <%= @inner_content %>
</main>

lib/car_dealership_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="csrf-token" content={csrf_token_value()} />
    <%= live_title_tag(assigns[:page_title] || "CarDealership", suffix: " · Phoenix Framework") %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <script
      defer
      phx-track-static
      type="text/javascript"
      src={Routes.static_path(@conn, "/assets/app.js")}
    >
    </script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css" />

    <script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js">
    </script>
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
      integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/fontawesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/brands.min.css"
    />

    <script src="https://cdn.ckeditor.com/4.11.1/standard/ckeditor.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js ">
    </script>

    <script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js">
    </script>

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.min.js"
      integrity="sha512-7U4rRB8aGAHGVad3u2jiC7GA5/1YhQcQjxKeaVms/bT66i3LVBMRcBI9KwABNWnxOSwulkuSXxZLGuyfvo7V1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    >
    </script>
    <script src="https://cdn.tailwindcss.com">
    </script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.css" rel="stylesheet" />
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.js">
      <script
        src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.js"
      >
    </script>
  </head>
  <body>
    <%= render("_user_menu.html", assigns) %>
    <%= @inner_content %>
    
  </body>
</html>